apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-apache
  namespace: default
  labels:
    app: apache-target
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-target
  template:
    metadata:
      labels:
        app: apache-target
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:22.04
        # Apache 설치 및 실행 명령
        command: ["/bin/bash", "-c"]
        args:
          - apt update && 
            apt install -y apache2 && 
            echo "Original Content" > /var/www/html/index.html &&
            apache2ctl -D FOREGROUND
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: apache-target
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # 나중에 브라우저에서 확인할 포트 (30000~32767 중 선택)
